# Generated by Django 4.2.6 on 2023-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
    ]
